package com.siec_acc.dto.request;

import com.siec_acc.enum_status.CurrencyType;
import com.siec_acc.enum_status.InvoiceStatus;
import com.siec_acc.enum_status.PaymentMode;

import jakarta.validation.constraints.NotNull;
import lombok.Builder;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Payload for creating/updating a TAX INVOICE.
 * invoiceStrId is generated by the service on create — never accepted from the client.
 */
@Builder
public class InvoiceRequestDto {

    @NotNull(message = "Invoice date is required")
    private LocalDate invoiceDate;

    private LocalDate invoiceDueDate;
    private Long invoiceCustomerId;

    // ---- Customer snapshot — populated by service from the customer
    // record, but accepted here too in case the frontend already resolved it. ----
    private String invoiceCustomerName;
    private String invoiceCustomerGst;
    private String invoiceCustomerEmail;
    private String invoiceCustomerState;
    private String invoiceCustomerStateCode;
    private String invoiceCustomerAddress;
    private String invoiceShippingAddress;

    private CurrencyType invoiceCurrency;

    private BigDecimal invoiceExchangeRate;
    private List<InvoiceItemRequestDto> invoiceItems;

    private BigDecimal invoiceDiscountPercent;
    private BigDecimal invoiceTaxPercent;
    private BigDecimal invoiceShippingCharges;
    private BigDecimal invoiceOtherCharges;
    private BigDecimal invoiceRoundOff;

    // Optional on create (defaults to UNPAID); required to move status on update.
    private InvoiceStatus invoiceStatus;

    private BigDecimal invoicePaidAmount;

    private String invoicePlaceOfSupply;
    private String invoiceTerms;
    private String invoiceNotes;
    private String invoiceReferenceNumber;
    private String invoicePoNumber;
    private String invoiceEwayBillNumber;
    private PaymentMode invoicePaymentMode;

    private String invoiceAttachmentUrl;
    private String invoiceSignatureUrl;
    private String invoiceAuthorizedSignatory;

    private Boolean invoiceIsRecurring;
    private String invoiceRecurringFrequency;

    // Set internally when this invoice is generated from ProformaService#convertToInvoice —
    // ignored if sent by the client directly.
    private Long invoiceConvertedFromProformaId;

    // Saved "Choose Template" selection to apply to this invoice's PDF.
    private String invoiceTemplateId;

    public InvoiceRequestDto(){}

    public InvoiceRequestDto(LocalDate invoiceDate, LocalDate invoiceDueDate, Long invoiceCustomerId, String invoiceCustomerName, String invoiceCustomerGst, String invoiceCustomerEmail, String invoiceCustomerState, String invoiceCustomerStateCode, String invoiceCustomerAddress, String invoiceShippingAddress, CurrencyType invoiceCurrency, BigDecimal invoiceExchangeRate, List<InvoiceItemRequestDto> invoiceItems, BigDecimal invoiceDiscountPercent, BigDecimal invoiceTaxPercent, BigDecimal invoiceShippingCharges, BigDecimal invoiceOtherCharges, BigDecimal invoiceRoundOff, InvoiceStatus invoiceStatus, BigDecimal invoicePaidAmount, String invoicePlaceOfSupply, String invoiceTerms, String invoiceNotes, String invoiceReferenceNumber, String invoicePoNumber, String invoiceEwayBillNumber, PaymentMode invoicePaymentMode, String invoiceAttachmentUrl, String invoiceSignatureUrl, String invoiceAuthorizedSignatory, Boolean invoiceIsRecurring, String invoiceRecurringFrequency, Long invoiceConvertedFromProformaId, String invoiceTemplateId) {
        this.invoiceDate = invoiceDate;
        this.invoiceDueDate = invoiceDueDate;
        this.invoiceCustomerId = invoiceCustomerId;
        this.invoiceCustomerName = invoiceCustomerName;
        this.invoiceCustomerGst = invoiceCustomerGst;
        this.invoiceCustomerEmail = invoiceCustomerEmail;
        this.invoiceCustomerState = invoiceCustomerState;
        this.invoiceCustomerStateCode = invoiceCustomerStateCode;
        this.invoiceCustomerAddress = invoiceCustomerAddress;
        this.invoiceShippingAddress = invoiceShippingAddress;
        this.invoiceCurrency = invoiceCurrency;
        this.invoiceExchangeRate = invoiceExchangeRate;
        this.invoiceItems = invoiceItems;
        this.invoiceDiscountPercent = invoiceDiscountPercent;
        this.invoiceTaxPercent = invoiceTaxPercent;
        this.invoiceShippingCharges = invoiceShippingCharges;
        this.invoiceOtherCharges = invoiceOtherCharges;
        this.invoiceRoundOff = invoiceRoundOff;
        this.invoiceStatus = invoiceStatus;
        this.invoicePaidAmount = invoicePaidAmount;
        this.invoicePlaceOfSupply = invoicePlaceOfSupply;
        this.invoiceTerms = invoiceTerms;
        this.invoiceNotes = invoiceNotes;
        this.invoiceReferenceNumber = invoiceReferenceNumber;
        this.invoicePoNumber = invoicePoNumber;
        this.invoiceEwayBillNumber = invoiceEwayBillNumber;
        this.invoicePaymentMode = invoicePaymentMode;
        this.invoiceAttachmentUrl = invoiceAttachmentUrl;
        this.invoiceSignatureUrl = invoiceSignatureUrl;
        this.invoiceAuthorizedSignatory = invoiceAuthorizedSignatory;
        this.invoiceIsRecurring = invoiceIsRecurring;
        this.invoiceRecurringFrequency = invoiceRecurringFrequency;
        this.invoiceConvertedFromProformaId = invoiceConvertedFromProformaId;
        this.invoiceTemplateId = invoiceTemplateId;
    }

    public LocalDate getInvoiceDate() {
        return invoiceDate;
    }

    public void setInvoiceDate(LocalDate invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    public LocalDate getInvoiceDueDate() {
        return invoiceDueDate;
    }

    public void setInvoiceDueDate(LocalDate invoiceDueDate) {
        this.invoiceDueDate = invoiceDueDate;
    }

    public Long getInvoiceCustomerId() {
        return invoiceCustomerId;
    }

    public void setInvoiceCustomerId(Long invoiceCustomerId) {
        this.invoiceCustomerId = invoiceCustomerId;
    }

    public String getInvoiceCustomerName() {
        return invoiceCustomerName;
    }

    public void setInvoiceCustomerName(String invoiceCustomerName) {
        this.invoiceCustomerName = invoiceCustomerName;
    }

    public String getInvoiceCustomerGst() {
        return invoiceCustomerGst;
    }

    public void setInvoiceCustomerGst(String invoiceCustomerGst) {
        this.invoiceCustomerGst = invoiceCustomerGst;
    }

    public String getInvoiceCustomerEmail() {
        return invoiceCustomerEmail;
    }

    public void setInvoiceCustomerEmail(String invoiceCustomerEmail) {
        this.invoiceCustomerEmail = invoiceCustomerEmail;
    }

    public String getInvoiceCustomerState() {
        return invoiceCustomerState;
    }

    public void setInvoiceCustomerState(String invoiceCustomerState) {
        this.invoiceCustomerState = invoiceCustomerState;
    }

    public String getInvoiceCustomerStateCode() {
        return invoiceCustomerStateCode;
    }

    public void setInvoiceCustomerStateCode(String invoiceCustomerStateCode) {
        this.invoiceCustomerStateCode = invoiceCustomerStateCode;
    }

    public String getInvoiceCustomerAddress() {
        return invoiceCustomerAddress;
    }

    public void setInvoiceCustomerAddress(String invoiceCustomerAddress) {
        this.invoiceCustomerAddress = invoiceCustomerAddress;
    }

    public String getInvoiceShippingAddress() {
        return invoiceShippingAddress;
    }

    public void setInvoiceShippingAddress(String invoiceShippingAddress) {
        this.invoiceShippingAddress = invoiceShippingAddress;
    }

    public CurrencyType getInvoiceCurrency() {
        return invoiceCurrency;
    }

    public void setInvoiceCurrency(CurrencyType invoiceCurrency) {
        this.invoiceCurrency = invoiceCurrency;
    }

    public BigDecimal getInvoiceExchangeRate() {
        return invoiceExchangeRate;
    }

    public void setInvoiceExchangeRate(BigDecimal invoiceExchangeRate) {
        this.invoiceExchangeRate = invoiceExchangeRate;
    }

    public List<InvoiceItemRequestDto> getInvoiceItems() {
        return invoiceItems;
    }

    public void setInvoiceItems(List<InvoiceItemRequestDto> invoiceItems) {
        this.invoiceItems = invoiceItems;
    }

    public BigDecimal getInvoiceDiscountPercent() {
        return invoiceDiscountPercent;
    }

    public void setInvoiceDiscountPercent(BigDecimal invoiceDiscountPercent) {
        this.invoiceDiscountPercent = invoiceDiscountPercent;
    }

    public BigDecimal getInvoiceTaxPercent() {
        return invoiceTaxPercent;
    }

    public void setInvoiceTaxPercent(BigDecimal invoiceTaxPercent) {
        this.invoiceTaxPercent = invoiceTaxPercent;
    }

    public BigDecimal getInvoiceShippingCharges() {
        return invoiceShippingCharges;
    }

    public void setInvoiceShippingCharges(BigDecimal invoiceShippingCharges) {
        this.invoiceShippingCharges = invoiceShippingCharges;
    }

    public BigDecimal getInvoiceOtherCharges() {
        return invoiceOtherCharges;
    }

    public void setInvoiceOtherCharges(BigDecimal invoiceOtherCharges) {
        this.invoiceOtherCharges = invoiceOtherCharges;
    }

    public BigDecimal getInvoiceRoundOff() {
        return invoiceRoundOff;
    }

    public void setInvoiceRoundOff(BigDecimal invoiceRoundOff) {
        this.invoiceRoundOff = invoiceRoundOff;
    }

    public InvoiceStatus getInvoiceStatus() {
        return invoiceStatus;
    }

    public void setInvoiceStatus(InvoiceStatus invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    public BigDecimal getInvoicePaidAmount() {
        return invoicePaidAmount;
    }

    public void setInvoicePaidAmount(BigDecimal invoicePaidAmount) {
        this.invoicePaidAmount = invoicePaidAmount;
    }

    public String getInvoicePlaceOfSupply() {
        return invoicePlaceOfSupply;
    }

    public void setInvoicePlaceOfSupply(String invoicePlaceOfSupply) {
        this.invoicePlaceOfSupply = invoicePlaceOfSupply;
    }

    public String getInvoiceTerms() {
        return invoiceTerms;
    }

    public void setInvoiceTerms(String invoiceTerms) {
        this.invoiceTerms = invoiceTerms;
    }

    public String getInvoiceNotes() {
        return invoiceNotes;
    }

    public void setInvoiceNotes(String invoiceNotes) {
        this.invoiceNotes = invoiceNotes;
    }

    public String getInvoiceReferenceNumber() {
        return invoiceReferenceNumber;
    }

    public void setInvoiceReferenceNumber(String invoiceReferenceNumber) {
        this.invoiceReferenceNumber = invoiceReferenceNumber;
    }

    public String getInvoicePoNumber() {
        return invoicePoNumber;
    }

    public void setInvoicePoNumber(String invoicePoNumber) {
        this.invoicePoNumber = invoicePoNumber;
    }

    public String getInvoiceEwayBillNumber() {
        return invoiceEwayBillNumber;
    }

    public void setInvoiceEwayBillNumber(String invoiceEwayBillNumber) {
        this.invoiceEwayBillNumber = invoiceEwayBillNumber;
    }

    public PaymentMode getInvoicePaymentMode() {
        return invoicePaymentMode;
    }

    public void setInvoicePaymentMode(PaymentMode invoicePaymentMode) {
        this.invoicePaymentMode = invoicePaymentMode;
    }

    public String getInvoiceAttachmentUrl() {
        return invoiceAttachmentUrl;
    }

    public void setInvoiceAttachmentUrl(String invoiceAttachmentUrl) {
        this.invoiceAttachmentUrl = invoiceAttachmentUrl;
    }

    public String getInvoiceSignatureUrl() {
        return invoiceSignatureUrl;
    }

    public void setInvoiceSignatureUrl(String invoiceSignatureUrl) {
        this.invoiceSignatureUrl = invoiceSignatureUrl;
    }

    public String getInvoiceAuthorizedSignatory() {
        return invoiceAuthorizedSignatory;
    }

    public void setInvoiceAuthorizedSignatory(String invoiceAuthorizedSignatory) {
        this.invoiceAuthorizedSignatory = invoiceAuthorizedSignatory;
    }

    public Boolean getInvoiceIsRecurring() {
        return invoiceIsRecurring;
    }

    public void setInvoiceIsRecurring(Boolean invoiceIsRecurring) {
        this.invoiceIsRecurring = invoiceIsRecurring;
    }

    public String getInvoiceRecurringFrequency() {
        return invoiceRecurringFrequency;
    }

    public void setInvoiceRecurringFrequency(String invoiceRecurringFrequency) {
        this.invoiceRecurringFrequency = invoiceRecurringFrequency;
    }

    public Long getInvoiceConvertedFromProformaId() {
        return invoiceConvertedFromProformaId;
    }

    public void setInvoiceConvertedFromProformaId(Long invoiceConvertedFromProformaId) {
        this.invoiceConvertedFromProformaId = invoiceConvertedFromProformaId;
    }

    public String getInvoiceTemplateId() {
        return invoiceTemplateId;
    }

    public void setInvoiceTemplateId(String invoiceTemplateId) {
        this.invoiceTemplateId = invoiceTemplateId;
    }
}
