package com.siec_acc.service.serviceImpl;

import com.siec_acc.dto.request.PurchasePatchDto;
import com.siec_acc.dto.request.PurchaseRequestDto;
import com.siec_acc.dto.response.PurchaseResponseDto;
import com.siec_acc.entity.PurchaseEntity;
import com.siec_acc.exceptions.InvalidOperationException;
import com.siec_acc.exceptions.ResourceNotFoundException;
import com.siec_acc.repository.PurchaseRepository;
import com.siec_acc.service.PurchaseService;
import com.siec_acc.utils.StrIdGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;

@Service
public class PurchaseServiceImpl implements PurchaseService {

    private static final Logger logger = LoggerFactory.getLogger(PurchaseServiceImpl.class);

    // Server may run in UTC; "today" for business rules is India time.
    private static final ZoneId BUSINESS_ZONE = ZoneId.of("Asia/Kolkata");

    private static final String STATUS_PENDING = "pending";
    private static final String STATUS_APPROVED = "approved";
    private static final String STATUS_REJECTED = "rejected";
    private static final Set<String> ALLOWED_STATUSES = Set.of(STATUS_PENDING, STATUS_APPROVED, STATUS_REJECTED);

    private static final String DEFAULT_PRIORITY = "medium";
    private static final Set<String> ALLOWED_PRIORITIES = Set.of("low", DEFAULT_PRIORITY, "high");

    private static final String DEFAULT_UNIT = "Pcs";

    private final PurchaseRepository purchaseRepository;

    public PurchaseServiceImpl(PurchaseRepository purchaseRepository) {
        this.purchaseRepository = purchaseRepository;
    }

    // ------------------------------------------------------------------
    // CREATE
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public PurchaseResponseDto createPurchase(PurchaseRequestDto dto) {
        logger.info("Creating new purchase requirement for item: {}", dto.getItemName());

        validateRequiredDate(dto.getRequiredDate(), null);

        PurchaseEntity purchase = new PurchaseEntity();
        purchase.setItemName(dto.getItemName().trim());
        purchase.setQuantity(dto.getQuantity());
        purchase.setUnit(blankToDefault(dto.getUnit(), DEFAULT_UNIT));
        purchase.setRequestedBy(dto.getRequestedBy().trim());
        purchase.setDepartment(trimToNull(dto.getDepartment()));
        purchase.setRequiredDate(dto.getRequiredDate());
        purchase.setPriority(isBlank(dto.getPriority()) ? DEFAULT_PRIORITY : normalizePriority(dto.getPriority()));
        purchase.setStatus(isBlank(dto.getStatus()) ? STATUS_PENDING : normalizeStatus(dto.getStatus()));
        purchase.setRemarks(trimToNull(dto.getRemarks()));

        // First save gets the DB id; the number is always generated by the server.
        PurchaseEntity saved = purchaseRepository.save(purchase);
        saved.setPurchaseStrId(StrIdGenerator.generate("PUR", saved.getPurchasePrimeId()));
        saved.setPurchaseNumber("PR-" + (1000 + saved.getPurchasePrimeId()));
        saved = purchaseRepository.save(saved);

        logger.info("PurchaseEntity created successfully: {}", saved.getPurchaseStrId());
        return mapToResponse(saved);
    }

    // ------------------------------------------------------------------
    // UPDATE (PUT) — required fields are validated by the DTO;
    // optional ones (priority/status) keep their old value when not sent.
    // purchaseNumber is never changed here.
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public PurchaseResponseDto updatePurchase(String purchaseStrId, PurchaseRequestDto dto) {
        logger.info("Updating purchase: {}", purchaseStrId);
        PurchaseEntity purchase = getPurchaseEntityOrThrow(purchaseStrId);

        validateRequiredDate(dto.getRequiredDate(), purchase.getRequiredDate());

        purchase.setItemName(dto.getItemName().trim());
        purchase.setQuantity(dto.getQuantity());
        purchase.setUnit(blankToDefault(dto.getUnit(), DEFAULT_UNIT));
        purchase.setRequestedBy(dto.getRequestedBy().trim());
        purchase.setDepartment(trimToNull(dto.getDepartment()));
        purchase.setRequiredDate(dto.getRequiredDate());
        purchase.setRemarks(trimToNull(dto.getRemarks()));
        if (!isBlank(dto.getPriority())) {
            purchase.setPriority(normalizePriority(dto.getPriority()));
        }
        applyStatusChange(purchase, dto.getStatus());

        PurchaseEntity updated = purchaseRepository.save(purchase);

        logger.info("PurchaseEntity updated successfully: {}", purchaseStrId);
        return mapToResponse(updated);
    }

    // ------------------------------------------------------------------
    // PATCH — only non-null fields are applied
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public PurchaseResponseDto patchPurchase(String purchaseStrId, PurchasePatchDto dto) {
        logger.info("Patching purchase: {}", purchaseStrId);
        PurchaseEntity purchase = getPurchaseEntityOrThrow(purchaseStrId);

        if (dto.getItemName() != null) purchase.setItemName(dto.getItemName().trim());
        if (dto.getQuantity() != null) purchase.setQuantity(dto.getQuantity());
        if (dto.getUnit() != null) purchase.setUnit(blankToDefault(dto.getUnit(), DEFAULT_UNIT));
        if (dto.getRequestedBy() != null) purchase.setRequestedBy(dto.getRequestedBy().trim());
        if (dto.getDepartment() != null) purchase.setDepartment(trimToNull(dto.getDepartment()));
        if (dto.getRequiredDate() != null) {
            validateRequiredDate(dto.getRequiredDate(), purchase.getRequiredDate());
            purchase.setRequiredDate(dto.getRequiredDate());
        }
        if (!isBlank(dto.getPriority())) purchase.setPriority(normalizePriority(dto.getPriority()));
        if (dto.getRemarks() != null) purchase.setRemarks(trimToNull(dto.getRemarks()));
        applyStatusChange(purchase, dto.getStatus());

        PurchaseEntity patched = purchaseRepository.save(purchase);

        logger.info("PurchaseEntity patched successfully: {}", purchaseStrId);
        return mapToResponse(patched);
    }

    // ------------------------------------------------------------------
    // DELETE
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public void deletePurchase(String purchaseStrId) {
        logger.info("Deleting purchase: {}", purchaseStrId);
        PurchaseEntity purchase = getPurchaseEntityOrThrow(purchaseStrId);
        purchaseRepository.delete(purchase);
        logger.info("PurchaseEntity deleted successfully: {}", purchaseStrId);
    }

    // ------------------------------------------------------------------
    // READS
    // ------------------------------------------------------------------
    @Override
    @Transactional(readOnly = true)
    public PurchaseResponseDto getPurchaseByStrId(String purchaseStrId) {
        logger.info("Fetching purchase: {}", purchaseStrId);
        return mapToResponse(getPurchaseEntityOrThrow(purchaseStrId));
    }

    @Override
    @Transactional(readOnly = true)
    public List<PurchaseResponseDto> getAllPurchases() {
        logger.info("Fetching all purchase requirements");
        return purchaseRepository.findAllByOrderByCreatedAtDesc().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<PurchaseResponseDto> getPurchasesByStatus(String status) {
        String normalized = normalizeStatus(status); // rejects unknown statuses with a clear message
        logger.info("Fetching purchases with status: {}", normalized);
        return purchaseRepository.findByStatusIgnoreCaseOrderByCreatedAtDesc(normalized).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<PurchaseResponseDto> getPurchasesByDepartment(String department) {
        logger.info("Fetching purchases for department: {}", department);
        return purchaseRepository.findByDepartmentIgnoreCaseOrderByCreatedAtDesc(department.trim()).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    // ------------------------------------------------------------------
    // APPROVE / REJECT — only allowed from "pending"
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public PurchaseResponseDto approvePurchase(String purchaseStrId) {
        logger.info("Approving purchase: {}", purchaseStrId);
        PurchaseEntity purchase = getPurchaseEntityOrThrow(purchaseStrId);
        requirePending(purchase, "approved");

        purchase.setStatus(STATUS_APPROVED);
        purchase.setRejectionReason(null);
        return mapToResponse(purchaseRepository.save(purchase));
    }

    @Override
    @Transactional
    public PurchaseResponseDto rejectPurchase(String purchaseStrId, String reason) {
        logger.info("Rejecting purchase: {}", purchaseStrId);
        PurchaseEntity purchase = getPurchaseEntityOrThrow(purchaseStrId);
        requirePending(purchase, "rejected");

        purchase.setStatus(STATUS_REJECTED);
        purchase.setRejectionReason(trimToNull(reason)); // original remarks are left untouched
        return mapToResponse(purchaseRepository.save(purchase));
    }

    // ------------------------------------------------------------------
    // helpers
    // ------------------------------------------------------------------
    private PurchaseEntity getPurchaseEntityOrThrow(String purchaseStrId) {
        return purchaseRepository.findByPurchaseStrId(purchaseStrId)
                .orElseThrow(() -> {
                    logger.warn("PurchaseEntity not found: {}", purchaseStrId);
                    return new ResourceNotFoundException("No purchase requirement found with ID '" + purchaseStrId + "'.");
                });
    }

    private void requirePending(PurchaseEntity purchase, String targetStatus) {
        if (!STATUS_PENDING.equalsIgnoreCase(purchase.getStatus())) {
            throw new InvalidOperationException(
                    "Only pending requirements can be " + targetStatus + ". "
                            + purchase.getPurchaseNumber() + " is currently " + purchase.getStatus() + ".");
        }
    }

    /**
     * Applies a status coming from PUT/PATCH.
     * A requirement that was already converted to a Purchase Order must stay approved.
     */
    private void applyStatusChange(PurchaseEntity purchase, String rawStatus) {
        if (isBlank(rawStatus)) return;
        String newStatus = normalizeStatus(rawStatus);
        if (newStatus.equalsIgnoreCase(purchase.getStatus())) return;

        if (!isBlank(purchase.getConvertedPoNumber())) {
            throw new InvalidOperationException(
                    purchase.getPurchaseNumber() + " is already converted to " + purchase.getConvertedPoNumber()
                            + ", so its status cannot be changed.");
        }
        purchase.setStatus(newStatus);
        if (!STATUS_REJECTED.equals(newStatus)) {
            purchase.setRejectionReason(null);
        }
    }

    /** Required date cannot be in the past — unless it is unchanged from what is already stored. */
    private void validateRequiredDate(LocalDate newDate, LocalDate oldDate) {
        if (newDate == null) return;
        LocalDate today = LocalDate.now(BUSINESS_ZONE);
        if (newDate.isBefore(today) && !newDate.equals(oldDate)) {
            throw new InvalidOperationException("Required date cannot be in the past.");
        }
    }

    private String normalizeStatus(String raw) {
        String s = raw == null ? "" : raw.trim().toLowerCase(Locale.ROOT);
        if (!ALLOWED_STATUSES.contains(s)) {
            throw new InvalidOperationException("Invalid status '" + raw + "'. Allowed: pending, approved, rejected.");
        }
        return s;
    }

    private String normalizePriority(String raw) {
        String p = raw == null ? "" : raw.trim().toLowerCase(Locale.ROOT);
        if (!ALLOWED_PRIORITIES.contains(p)) {
            throw new InvalidOperationException("Invalid priority '" + raw + "'. Allowed: low, medium, high.");
        }
        return p;
    }

    private boolean isBlank(String s) {
        return s == null || s.isBlank();
    }

    private String trimToNull(String s) {
        return (s == null || s.isBlank()) ? null : s.trim();
    }

    private String blankToDefault(String s, String fallback) {
        return (s == null || s.isBlank()) ? fallback : s.trim();
    }

    private PurchaseResponseDto mapToResponse(PurchaseEntity purchase) {
        return new PurchaseResponseDto(
                purchase.getPurchasePrimeId(),
                purchase.getPurchaseStrId(),
                purchase.getPurchaseNumber(),
                purchase.getItemName(),
                purchase.getQuantity(),
                purchase.getUnit(),
                purchase.getRequestedBy(),
                purchase.getDepartment(),
                purchase.getRequiredDate(),
                purchase.getPriority(),
                purchase.getStatus(),
                purchase.getRemarks(),
                purchase.getRejectionReason(),
                purchase.getConvertedPoNumber(),
                purchase.getCreatedAt(),
                purchase.getUpdatedAt()
        );
    }
}