package com.siec_acc.service.serviceImpl;

import com.siec_acc.dto.request.PurchaseOrderItemRequestDto;
import com.siec_acc.dto.request.PurchaseOrderPatchDto;
import com.siec_acc.dto.request.PurchaseOrderRequestDto;
import com.siec_acc.dto.response.PurchaseOrderItemResponseDto;
import com.siec_acc.dto.response.PurchaseOrderResponseDto;
import com.siec_acc.entity.PurchaseEntity;
import com.siec_acc.entity.PurchaseOrderEntity;
import com.siec_acc.entity.PurchaseOrderItemEntity;
import com.siec_acc.exceptions.InvalidOperationException;
import com.siec_acc.exceptions.ResourceNotFoundException;
import com.siec_acc.repository.GoodsReceiptRepository;
import com.siec_acc.repository.PurchaseBillRepository;
import com.siec_acc.repository.PurchaseOrderRepository;
import com.siec_acc.repository.PurchaseRepository;
import com.siec_acc.service.PurchaseOrderService;
import com.siec_acc.utils.StrIdGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;

@Service
public class PurchaseOrderServiceImpl implements PurchaseOrderService {

    private static final Logger logger = LoggerFactory.getLogger(PurchaseOrderServiceImpl.class);

    private static final String DEFAULT_STATUS = "draft";
    private static final Set<String> ALLOWED_STATUSES =
            Set.of("draft", "approved", "sent", "partial", "fully_received", "closed");
    private static final String DEFAULT_UNIT = "Pcs";
    private static final String PR_STATUS_APPROVED = "approved";

    private final PurchaseOrderRepository purchaseOrderRepository;
    private final PurchaseRepository purchaseRepository;         // to read/patch the source Purchase Requirement
    private final PurchaseBillRepository purchaseBillRepository; // to block deleting a PO that has bills
    private final GoodsReceiptRepository goodsReceiptRepository; // to block deleting a PO / shrinking items below received qty

    public PurchaseOrderServiceImpl(PurchaseOrderRepository purchaseOrderRepository,
                                    PurchaseRepository purchaseRepository,
                                    PurchaseBillRepository purchaseBillRepository,
                                    GoodsReceiptRepository goodsReceiptRepository) {
        this.purchaseOrderRepository = purchaseOrderRepository;
        this.purchaseRepository = purchaseRepository;
        this.purchaseBillRepository = purchaseBillRepository;
        this.goodsReceiptRepository = goodsReceiptRepository;
    }

    // ------------------------------------------------------------------
    // CREATE
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public PurchaseOrderResponseDto createPurchaseOrder(PurchaseOrderRequestDto dto) {
        logger.info("Creating new purchase order for vendor: {}", dto.getVendorName());

        validateDates(dto.getPoDate(), dto.getDeliveryDate());
        validateTax(dto.getTaxPct());
        validateItems(dto.getItems());

        PurchaseEntity sourcePurchase = resolveSourcePurchase(dto.getSourcePurchaseStrId());

        PurchaseOrderEntity po = new PurchaseOrderEntity();
        po.setVendorName(dto.getVendorName().trim());
        po.setPoDate(dto.getPoDate());
        po.setDeliveryDate(dto.getDeliveryDate());
        po.setTaxPct(dto.getTaxPct() == null ? 0.0 : dto.getTaxPct());
        po.setStatus(isBlank(dto.getStatus()) ? DEFAULT_STATUS : normalizeStatus(dto.getStatus()));
        po.setItems(toItemEntities(dto.getItems()));
        po.setSourcePurchaseStrId(sourcePurchase != null ? sourcePurchase.getPurchaseStrId() : null);

        // First save gets the DB id; the number is always generated by the server.
        PurchaseOrderEntity saved = purchaseOrderRepository.save(po);
        saved.setPoStrId(StrIdGenerator.generate("PO", saved.getPoPrimeId()));
        saved.setPoNumber("PO-" + (2000 + saved.getPoPrimeId()));
        saved = purchaseOrderRepository.save(saved);

        if (sourcePurchase != null) {
            sourcePurchase.setConvertedPoNumber(saved.getPoNumber());
            purchaseRepository.save(sourcePurchase);
            logger.info("Linked {} to newly created {}", sourcePurchase.getPurchaseNumber(), saved.getPoNumber());
        }

        logger.info("PurchaseOrderEntity created successfully: {}", saved.getPoStrId());
        return mapToResponse(saved);
    }

    // ------------------------------------------------------------------
    // UPDATE (PUT) — poNumber and sourcePurchaseStrId are never changed here.
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public PurchaseOrderResponseDto updatePurchaseOrder(String poStrId, PurchaseOrderRequestDto dto) {
        logger.info("Updating purchase order: {}", poStrId);
        PurchaseOrderEntity po = getEntityOrThrow(poStrId);

        validateDates(dto.getPoDate(), dto.getDeliveryDate());
        validateTax(dto.getTaxPct());
        validateItems(dto.getItems());

        po.setVendorName(dto.getVendorName().trim());
        po.setPoDate(dto.getPoDate());
        po.setDeliveryDate(dto.getDeliveryDate());
        po.setTaxPct(dto.getTaxPct() == null ? 0.0 : dto.getTaxPct());
        guardItemsAgainstReceipts(po, dto.getItems());
        po.setItems(toItemEntities(dto.getItems()));
        if (!isBlank(dto.getStatus())) {
            po.setStatus(normalizeStatus(dto.getStatus()));
        }

        PurchaseOrderEntity updated = purchaseOrderRepository.save(po);
        logger.info("PurchaseOrderEntity updated successfully: {}", poStrId);
        return mapToResponse(updated);
    }

    // ------------------------------------------------------------------
    // PATCH — only non-null fields are applied
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public PurchaseOrderResponseDto patchPurchaseOrder(String poStrId, PurchaseOrderPatchDto dto) {
        logger.info("Patching purchase order: {}", poStrId);
        PurchaseOrderEntity po = getEntityOrThrow(poStrId);

        LocalDate newPoDate = dto.getPoDate() != null ? dto.getPoDate() : po.getPoDate();
        LocalDate newDeliveryDate = dto.getDeliveryDate() != null ? dto.getDeliveryDate() : po.getDeliveryDate();
        validateDates(newPoDate, newDeliveryDate);

        if (dto.getVendorName() != null) po.setVendorName(dto.getVendorName().trim());
        po.setPoDate(newPoDate);
        po.setDeliveryDate(newDeliveryDate);
        if (dto.getTaxPct() != null) {
            validateTax(dto.getTaxPct());
            po.setTaxPct(dto.getTaxPct());
        }
        if (dto.getItems() != null) {
            validateItems(dto.getItems());
            guardItemsAgainstReceipts(po, dto.getItems());
            po.setItems(toItemEntities(dto.getItems()));
        }
        if (!isBlank(dto.getStatus())) {
            po.setStatus(normalizeStatus(dto.getStatus()));
        }

        PurchaseOrderEntity patched = purchaseOrderRepository.save(po);
        logger.info("PurchaseOrderEntity patched successfully: {}", poStrId);
        return mapToResponse(patched);
    }

    // ------------------------------------------------------------------
    // DELETE — blocked if a purchase bill is already linked; releases the source PR, if any.
    // ------------------------------------------------------------------
    @Override
    @Transactional
    public void deletePurchaseOrder(String poStrId) {
        logger.info("Deleting purchase order: {}", poStrId);
        PurchaseOrderEntity po = getEntityOrThrow(poStrId);

        if (purchaseBillRepository.existsByPoNumberIgnoreCase(po.getPoNumber())) {
            throw new InvalidOperationException(
                    "Cannot delete " + po.getPoNumber() + ": one or more purchase bills are linked to it.");
        }

        if (goodsReceiptRepository.existsByPoStrId(po.getPoStrId())) {
            throw new InvalidOperationException(
                    "Cannot delete " + po.getPoNumber() + ": goods have already been received against it. Delete the goods receipts first.");
        }

        purchaseOrderRepository.delete(po);

        purchaseRepository.findByConvertedPoNumberIgnoreCase(po.getPoNumber()).ifPresent(pr -> {
            pr.setConvertedPoNumber(null);
            purchaseRepository.save(pr);
            logger.info("Released {} so it can be converted again", pr.getPurchaseNumber());
        });

        logger.info("PurchaseOrderEntity deleted successfully: {}", poStrId);
    }

    // ------------------------------------------------------------------
    // READS
    // ------------------------------------------------------------------
    @Override
    @Transactional(readOnly = true)
    public PurchaseOrderResponseDto getPurchaseOrderByStrId(String poStrId) {
        logger.info("Fetching purchase order: {}", poStrId);
        return mapToResponse(getEntityOrThrow(poStrId));
    }

    @Override
    @Transactional(readOnly = true)
    public List<PurchaseOrderResponseDto> getAllPurchaseOrders() {
        logger.info("Fetching all purchase orders");
        return purchaseOrderRepository.findAllByOrderByCreatedAtDesc().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<PurchaseOrderResponseDto> getPurchaseOrdersByStatus(String status) {
        String normalized = normalizeStatus(status);
        logger.info("Fetching purchase orders with status: {}", normalized);
        return purchaseOrderRepository.findByStatusIgnoreCaseOrderByCreatedAtDesc(normalized).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<PurchaseOrderResponseDto> getPurchaseOrdersByVendor(String vendorName) {
        logger.info("Fetching purchase orders for vendor: {}", vendorName);
        return purchaseOrderRepository.findByVendorNameContainingIgnoreCaseOrderByCreatedAtDesc(vendorName.trim()).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    // ------------------------------------------------------------------
    // helpers
    // ------------------------------------------------------------------
    private PurchaseOrderEntity getEntityOrThrow(String poStrId) {
        return purchaseOrderRepository.findByPoStrId(poStrId)
                .orElseThrow(() -> {
                    logger.warn("PurchaseOrderEntity not found: {}", poStrId);
                    return new ResourceNotFoundException("No purchase order found with ID '" + poStrId + "'.");
                });
    }

    /** Validates and resolves the Purchase Requirement being converted, if one was passed in. */
    private PurchaseEntity resolveSourcePurchase(String sourcePurchaseStrId) {
        if (isBlank(sourcePurchaseStrId)) return null;

        PurchaseEntity purchase = purchaseRepository.findByPurchaseStrId(sourcePurchaseStrId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No purchase requirement found with ID '" + sourcePurchaseStrId + "'."));

        if (!PR_STATUS_APPROVED.equalsIgnoreCase(purchase.getStatus())) {
            throw new InvalidOperationException(
                    "Only an approved purchase requirement can be converted to a purchase order. "
                            + purchase.getPurchaseNumber() + " is currently " + purchase.getStatus() + ".");
        }
        if (!isBlank(purchase.getConvertedPoNumber())) {
            throw new InvalidOperationException(
                    purchase.getPurchaseNumber() + " is already converted to " + purchase.getConvertedPoNumber() + ".");
        }
        return purchase;
    }

    /** Once goods are received, every received item must stay on the PO with a quantity >= what was received. */
    private void guardItemsAgainstReceipts(PurchaseOrderEntity po, List<PurchaseOrderItemRequestDto> newItems) {
        if (!goodsReceiptRepository.existsByPoStrId(po.getPoStrId())) return;
        java.util.Map<String, Integer> received = new java.util.HashMap<>();
        goodsReceiptRepository.findByPoStrIdOrderByGrnPrimeIdAsc(po.getPoStrId())
                .forEach(g -> received.merge(g.getItemName().trim().toLowerCase(Locale.ROOT), g.getReceivedQty(), Integer::sum));
        received.forEach((name, qty) -> {
            boolean ok = newItems.stream().anyMatch(it ->
                    it.getName() != null && it.getName().trim().toLowerCase(Locale.ROOT).equals(name)
                            && it.getQty() != null && it.getQty() >= qty);
            if (!ok) {
                throw new InvalidOperationException("Goods are already received on " + po.getPoNumber() + ": item '" + name
                        + "' must stay on the order with a quantity of at least " + qty + ".");
            }
        });
    }

    private void validateDates(LocalDate poDate, LocalDate deliveryDate) {
        if (poDate != null && deliveryDate != null && deliveryDate.isBefore(poDate)) {
            throw new InvalidOperationException("Delivery date cannot be before the PO date.");
        }
    }

    private void validateTax(Double taxPct) {
        if (taxPct != null && (taxPct < 0 || taxPct > 100)) {
            throw new InvalidOperationException("GST must be between 0 and 100.");
        }
    }

    private void validateItems(List<PurchaseOrderItemRequestDto> items) {
        if (items == null || items.isEmpty()) {
            throw new InvalidOperationException("Add at least one item.");
        }
        for (int i = 0; i < items.size(); i++) {
            PurchaseOrderItemRequestDto it = items.get(i);
            if (isBlank(it.getName())) {
                throw new InvalidOperationException("Item " + (i + 1) + ": enter an item name.");
            }
            if (it.getQty() == null || it.getQty() <= 0) {
                throw new InvalidOperationException("Item " + (i + 1) + ": quantity must be greater than 0.");
            }
            if (it.getRate() == null || it.getRate() <= 0) {
                throw new InvalidOperationException("Item " + (i + 1) + ": enter a rate greater than 0.");
            }
        }
    }

    private List<PurchaseOrderItemEntity> toItemEntities(List<PurchaseOrderItemRequestDto> items) {
        List<PurchaseOrderItemEntity> result = new ArrayList<>();
        for (PurchaseOrderItemRequestDto it : items) {
            result.add(new PurchaseOrderItemEntity(
                    it.getName().trim(),
                    it.getQty(),
                    blankToDefault(it.getUnit(), DEFAULT_UNIT),
                    it.getRate()
            ));
        }
        return result;
    }

    private String normalizeStatus(String raw) {
        String s = raw == null ? "" : raw.trim().toLowerCase(Locale.ROOT);
        if (!ALLOWED_STATUSES.contains(s)) {
            throw new InvalidOperationException(
                    "Invalid status '" + raw + "'. Allowed: draft, approved, sent, partial, fully_received, closed.");
        }
        return s;
    }

    private boolean isBlank(String s) {
        return s == null || s.isBlank();
    }

    private String blankToDefault(String s, String fallback) {
        return (s == null || s.isBlank()) ? fallback : s.trim();
    }

    private double round2(double n) {
        return Math.round(n * 100.0) / 100.0;
    }

    private PurchaseOrderResponseDto mapToResponse(PurchaseOrderEntity po) {
        List<PurchaseOrderItemResponseDto> itemDtos = po.getItems().stream()
                .map(it -> new PurchaseOrderItemResponseDto(
                        it.getItemId(), it.getName(), it.getQty(), it.getUnit(), it.getRate(),
                        round2(it.getQty() * it.getRate())))
                .collect(Collectors.toList());

        double subtotal = itemDtos.stream().mapToDouble(PurchaseOrderItemResponseDto::getAmount).sum();
        double taxPct = po.getTaxPct() == null ? 0.0 : po.getTaxPct();
        double taxAmount = round2(subtotal * taxPct / 100.0);
        double total = round2(subtotal + taxAmount);

        return new PurchaseOrderResponseDto(
                po.getPoPrimeId(),
                po.getPoStrId(),
                po.getPoNumber(),
                po.getVendorName(),
                po.getPoDate(),
                po.getDeliveryDate(),
                taxPct,
                po.getStatus(),
                po.getSourcePurchaseStrId(),
                itemDtos,
                round2(subtotal),
                taxAmount,
                total,
                po.getCreatedAt(),
                po.getUpdatedAt()
        );
    }
}
